#COMMENT
###
GET  http://localhost:3001/api/v1/commment/get?id=1

###
DELETE   http://localhost:3001/api/v1/comment/delete?id=4
###
PUT  http://localhost:3001/api/v1/comment/update?id=2
###
POST  http://localhost:3001/api/v1/comment/create?userId=2&productId=1
Content-Type: application/json

{
    "text": "Comment 1",
    "img": " < this will be a img and storge as a link > "
}