###
POST http://localhost:3001/api/v1/auth/login
Content-Type: application/json

{
    "email": "admin1@gmail.com",
    "password": "mothaibabon"
}
###
POST http://localhost:3001/api/v1/auth/changeinfo
Content-Type: application/json

{
    "email": "admin1@gmail.com",
    "fullname": "nyvmm"
}
###
GET http://localhost:3001/api/v1/user/get?userId=1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiYWRtaW4xQGdtYWlsLmNvbSIsImlhdCI6MTY4NTk5OTgyMCwiZXhwIjoxNjg2MDAwODIwfQ.imDSOPphJDeT-IJUN6p2yjz8P5jFoIFYVfp3WniwlKU

###
GET http://localhost:3001/api/v1/user/get-all
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiYWRtaW4xQGdtYWlsLmNvbSIsImlhdCI6MTY4NTk5OTgyMCwiZXhwIjoxNjg2MDAwODIwfQ.imDSOPphJDeT-IJUN6p2yjz8P5jFoIFYVfp3WniwlKU



#copy cái token nhận đc khi đăng nhập mà bỏ dô :>
###
POST http://localhost:3001/api/v1/auth/register
Content-Type: application/json

{
    "email": "admin11@gmail.com",
    "password": "password",
    "phone": "0123",
    "name": "vynmm"
}
